### ISSUE TITLE
JitPack: Build is broken (Downloader Subversion Unresolved reference: requestPasswordAuthenticationInstance)

### ISSUE THREAD

**Issue by andreaslarfors** [oss-review-toolkit/ort#3330]
The JitPack build appears to be broken since commit b1cbf50b49cd0d7230d295a6a21a585eb90e3538

JitPack error log:
```
> Task :downloader:compileKotlin FAILED
e: /home/jitpack/build/downloader/src/main/kotlin/vcs/Subversion.kt: (268, 46): Unresolved reference: requestPasswordAuthenticationInstance

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloader:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork
   > Compilation error. See log for more details
...
BUILD FAILED in 2m 21s
96 actionable tasks: 96 executed
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
[Fatal Error] pom.xml:1:1: Premature end of file.
```

Example: https://jitpack.io/com/github/oss-review-toolkit/ort/eb7d747de0/build.log

**Comment by sschuberth** [comment]
That's a side effect of @mnonnenmacher having to revert our [migration to Java 11](https://github.com/oss-review-toolkit/ort/pull/3326) for some internal reasons. @mnonnenmacher, are you still confident that you can restore my changes by today?

**Comment by mnonnenmacher** [comment]
Unfortunately not, all my test builds failed with the error below which prevented me from making progress. I will have to continue on Monday. As a workaround we could upgrade to Java 10 instead if it is urgent and would help, until I could fix the issue on our side.

```
Could not determine the dependencies of task ':cli:installDist'.
> Could not resolve all dependencies for configuration ':cli:runtimeClasspath'.
> A problem occurred configuring project ':clients:clearly-defined'.
> Could not open cache directory be2vyyzc82zj0yzd1epubxm40 (/home/.../.gradle/caches/6.7/gradle-kotlin-dsl/be2vyyzc82zj0yzd1epubxm40).
> org.gradle.api.internal.initialization.DefaultClassLoaderScope@30dddb0c must be locked before it can be used to compute a classpath!
```

**Comment by sschuberth** [comment]
@mnonnenmacher isn't this just https://github.com/oss-review-toolkit/ort/issues/3306?

**Comment by sschuberth** [comment]
Also see https://github.com/oss-review-toolkit/ort/pull/3333 that I just filed.

**Comment by mnonnenmacher** [comment]
@sschuberth Thanks for #3333, that helped. Yes, it was #3306, it just took a while to verify that everything works correctly now. I have restored your commits, so the JitPack build should work again.

**Comment by sschuberth** [comment]
The [JitPack build](https://jitpack.io/com/github/oss-review-toolkit/ort/0d7fa47e5c/build.log) for commit 0d7fa47e5c40b8ae50c3ea536a8eaa33d492dd05 succeeded, so I'm closing this.
